apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-service
  namespace: default
spec:
  selector:
    app: todo-frontend
  ports:
  - port: 80
    targetPort: 80
  type: NodePort  # This will expose it outside the cluster